RULES = [
    "Every expense must be linked to an active project or department; expenses submitted for projects marked as 'cancelled' or 'completed' are not permitted. Any expense lacking a valid project assignment is automatically declined.",
    "Team allocations determine project budgets—total allocated employee costs (calculated as hours multiplied by hourly rate) must not surpass 80% of the overall project budget. The remaining 20% is designated for non-personnel costs. If personnel expenses go beyond this limit, budget alerts are generated.",
    "Vendor payments are required to correspond with project schedules. Invoices for expenses tied to a project cannot be processed once the project end date has passed. Early payment discounts of 2% for payments made within 10 days are automatically granted when there is adequate surplus in the project budget.",
    "Approval requirements for purchase orders are determined by the priority level of their linked project. Projects marked as Critical priority are permitted to exceed standard PO limits. For Low priority projects, any purchase order exceeding $10,000 necessitates supplementary justification.",
    "Cost allocations are required to match the actual hours recorded by team members. If the difference between planned allocations and actual logged hours exceeds 15%, an automatic reallocation is initiated. Costs not assigned due to employees lacking logged hours are proportionally redistributed.",
    "Financial transactions are systematically associated with sprint deliverables. Expenses incurred during ongoing sprints must be tied to designated tasks. Upon sprint completion, budget reconciliation and variance reporting are performed automatically.",
    "Budget transfers adhere to the team hierarchy—transfers occurring within a single team need approval solely from the team lead. Transfers between different teams within the same department require coordination at the department level. Transfers spanning departments are subject to finance review.",
    "Expense reimbursement requests are checked against employee allocation records. Employees are permitted to submit reimbursements only for projects to which they are currently allocated. The reimbursement limit is proportional to the allocation percentage (a 100% allocation grants the full limit, while a 50% allocation provides half the limit).",
    "Quarterly budget reviews utilize team velocity and sprint performance metrics. Projects that consistently exceed sprint budgets receive automatic adjustments to their budgets. Projects demonstrating underperformance will have their budgets reduced in the subsequent quarter.",
    "When selecting vendors for projects, team expertise must be taken into account. For new vendors, a capability assessment against the team's skills is required. Vendors receive automatic ratings based on metrics for project completion and team feedback gathered from sprint retrospectives.",
]
