RULES = [
    "Tools may be invoked as necessary to accomplish the specified task.",
    "When utilizing the update_adset_status tool, set the new_status parameter to \"paused\" to pause an adset or to \"active\" to activate it.",
    "When operating the get_policy_param tool, the permitted parameters include: default_bid_strategy, max_daily_budget_total, min_roas_threshold_7d, creative_rotation_window_days, video_cpa_advantage_pct, budget_rounding_unit, currency, timezone, max_bid_amount, min_budget_allocation, canonical_bid_strategies, and canonical_creative_types.",
    "When applying the add_automation_run tool, assign the started_at and ended_at fields the timestamp value provided by the get_current_timestamp tool.",
    "When utilizing the add_automation_run tool, set the status to \"completed\" unless a different value is explicitly provided.",
    "When utilizing the add_automation_run tool, assign \"{}\" to errors_json unless another value is specifically indicated.",
    "When employing the add_campaign tool, assign the id as \"12\" unless an alternative is expressly specified.",
    "When utilizing the add_campaign tool, set created_date to \"2025-08-14\" unless a different value is explicitly provided.",
    "When utilizing the add_campaign tool, assign status as \"active\" unless another value is specifically indicated.",
    "When employing the add_adset tool to generate a new adset, assign id as \"114\" unless a different id is expressly specified.",
    "When creating a new adset with the add_adset tool, set bid_strategy to \"lowest_cost\" unless another value is explicitly provided.",
    "When creating a new adset with the add_adset tool, assign None to bid_amount unless a different value is specified.",
    "When using the add_automation_run tool, assign 'AR-APPLY-202508-01' to run_id unless an alternative is specified.",
    "When creating a new ad with the add_ads tool, set start_date to \"2025-08-14\" unless a different value is provided.",
    "When creating a new ad with the add_ad tool, assign None to end_date unless another value is specified.",
]