RULES = [
    "Always write task instructions in SECOND PERSON ('You ...').",
    "Avoid step-by-step phrasing. State goals, constraints, and success criteria.",
    "Actions must be executable with parameters deterministically derivable from the instruction, prior tool outputs, or these rules.",
    "IDs and timestamps are generated by the tools. Do not provide them in actions.",
    "When recording translations, each entry MUST ONLY include: string_key, locale, target_string. Do NOT pass an 'id'.",
    "Notification #1 (job queued): "
    "  notification_type='info', "
    "  title='Job queued: {string_key} [{targets}]', "
    "  message='TMS job created for {string_key}', "
    "  channel='slack'.",
    "Notification #2 (validations passed): "
    "  notification_type='update', "
    "  title='Validations passed: {string_key} [{targets}]', "
    "  message='Validations passed for {targets} for {string_key}', "
    "  channel='slack'.",
    "Default source locale is 'en' unless provided.",
    "TMS jobs require source_locale and at least one target_locale.",
    "The 'link_type' parameter is required for link_work_items.",
    "The 'notification_type' parameter is required for send_notification.",
    "Translation entries MUST NOT include 'id'. Tools will ignore any provided 'id' and generate deterministic IDs internally.",
]
