RULES = [
    ## Helpers
    "When using timestamp is needed always use the exact time specified in the instructions for the current time."
    "airport_id uses ARP_XYZ and airport iata code uses XYZ format. When passing to the args to the tool, be careful about what you send exactly and dont get confused which one to use, Always check with the tool spec. Use get_airport_by_code to get airport ID by using airports iata code when airport_id is needed."

    "delay_flight_actual_times_for_date: Shift flight times for {flight_number} on {date} by {delay_minutes} minutes (positive = delay, negative = advance)."
    "When given a full name, split as first token = first_name, remainder = last_name unless fields are explicitly provided. Pass names to tools exactly as normalized."

    "When directly instructed to ensure maintenance_logs for aircraft are reflected in the log run maintenance_logs_for_aircraft"
    "When directly instructed to ensure events at airport are reflected in the log run events_at_airport_on"
    "When gate-change happens accompanied by a delay. use delayed-gate-change as event type"
    "Group multiple flight status updates into a single update_flight_status_for_date call whenever possible unless otherwise specified."
    "When a delay and gate changes happen together use delayed-gate-change for flight status unless otherwise specified."
    ## protocols
    "Crew Recertification protocol: When a crew member is scheduled for recurrent or type-specific training, set their status to 'Training'. Verify the relevant certification code exists in their record and protect the roster by there is not conflicting duties on the training date. Log an operational event and user notification with the fixed format: 'Training scheduled for {crew_member_id} on {date} : {certification_code}.'"
    "The Aircraft AOG protocol defines that when an aircraft is grounded (AOG) at an airport , Update the aircraft status to In Maintenance, log the event with the fixed format: 'aircraft {tail_number} grounded for maintenance, {flight_number} on {date}.' , append a maintenance log with the same message and maintenance_type according to the context from allowed options. for create_operational_event and append_maintenance_log dont omit args if you have them in the context , use 'AIRCRAFT_AOG' for event type and 'Unscheduled' maintenance_type unless otherwise specified."
    "A SIGMET is a Weather event  for significant meteorological phenomena that may affect flight safety. The SIGMET delay protocol defines that when a SIGMET affects an airport, the event ( operational event type 'Weather' ) is logged with the SIGMET details in a fixed format: 'SIGMET impacts {airport_code} operations; apply {delay_minutes}-minutes delay to affected flights.' Affected flights are updated to 'delayed' and update the flight time for the date with the delay. Notify the passengers about the delay.",
    "Baggage Irregularity protocol (clarified): Event type = BAGGAGE_HANDLING; log at the destination airport with details exactly ‘Baggage Irregularity: {flight_number} from airport {origin_airport_id} to airport {destination_airport_id} on {date}.’ Then set status ‘baggage delay’; if equipment faults found, append the destination maintenance log with the given message; deterministic order: create event -> update status -> append maintenance log -> events_at_airport_on (origin then destination) "
    "Fuel Supply Disruption protocol: When a fuel shortage is reported at an airport, log the event in the fixed format: 'Fuel supply disruption at {airport_code} on {date}; priorities: {high_priority_flights_comma_separated_with_one_space_after_each_comma or None}' For each non-priority flight, update its status to 'canceled' as determined, then notify the airport's operations channel ( ops-{airport-code-lower} ) in the fixed format: 'Fuel program {airport_code}: {delayed_flights} delayed, {canceled_flights} canceled.' (delayed_flights are comma separated flight nubmers (one space after each comma), same for canceled_flights)}.'"
    "Last-Minute Crew Replacement protocol: When a crew member becomes unavailable , log the event 'Crew Replacement' with the fixed format: 'Last-minute crew replacement required for {flight_number} on {date}.' Identify a qualified substitute matching the required role, update the crew member status for the original member to 'On Leave'; if its due to sickness 'Sick Leave'; assign the substitute to the flight.",
    "Crew Duty-Limit Mitigation protocol: When assigned crew will exceed legal duty limits, log the event in the fixed format: 'Crew delay on {flight_number}; standby crew assigned: {crew_member_id}.' Update affected crew status to 'Inactive', assign standby crew"
    "Unattended Baggage protocol: When an unattended item is found at an airport, halt boarding for nearby flights in the same concourse, investigate by matching passenger reservations (find_reservations_by_flight_day) , update affected flight statuses to 'security-hold' until clearance, log the incident with event type UNATTENDED_BAGGAGE and message: 'Unattended baggage {place}; boarding paused for {flight_numbers}.' then then notify the airport's operations channel ( ops-{airport-code-lower} ) in the fixed format: 'Security advisory: temporary boarding pause for {flight_number} at {airport_code}.'}.'"
    "Flight cancellation protocol: Update the flight status to canceled; then notify the airport's operations channel ( ops-{airport_code_lower} ) in the fixed format:'Flight {flight_number} on {date} at {airport_code} canceled.'}'"
    "Connection Protection protocol: identify all passengers on the fight , check same-day departures from the airport, log a customer communication event, and notify passengers of the initiating flight with the fixed message: 'Connection protection advisory for {flight_number} on {date}: monitoring tight connections; alternatives under review.' Record event at {airport_id} with details exactly: 'Connection protection monitoring initiated for {flight_number}'"
    "Diplomatic Arrival protocol: When a diplomatic or high-security delegation is arriving, confirm aircraft status, validate all required special clearances, coordinate with airport security for secure handling from arrival to deplaning, log the event with event_type: 'Security Alert' in fixed format: 'Diplomatic arrival {flight_number}; secure handling from arrival to deplaning; protocol compliance confirmed.' Notify the airport's operations with the same confirmation message.",
    "Group Split Assistance protocol: confirm the flight, pull the manifest, identify bookings tied to customer IDs ,log a customer communication event , and notify the ops channel with: '{airport_iata_code} res: {flight_number} family group {[user_ids]} requires coordinated seat adjustments; support engaged.' Event details exactly: 'Group seating assistance initiated for HAT299 ({date}) for parties {[user_ids]}.' , event type: CUSTOMER_COMMUNICATION"
    "Duplicate Booking Advisory protocol: Record event exactly: 'Duplicate booking scan executed for {user_id}; potential overlaps flagged for review.' , Notify 'ops-bos' with: 'Duplicate booking advisory for customer {user_id}-review and consolidate if needed.'"
    "Refund protocol: Check the user reservations, Create operational event with the message: 'Reservation {reservation_id} refunded.' , Notify the user with the message: 'Reservation {reservation_id} refunded.'"
    "Involuntary downgrades protocol: Set the flight status to delayed. Record event exactly: 'Involuntary downgrade process started for {flight_number} ({date})' ,Notify operation channel with: '{flight_number} {date}: reduced cabin capacity.' event type 'CUSTOMER_COMMUNICATION'"
    "Duplicate-Name Manifest Audit protocol: Check if the incident is not already logged. Record event exactly: 'Duplicate-name audit executed for {flight_number} ({date}) at {airport_code}; identity checks initiated.' Notify operation channel with: 'Manifest audit: duplicate names on {flight_number} ({date}); ID verification in progress. Notify affected passengers ( reservation users ) with: 'Manifest audit: Flight {flight_number}; Bring IDs to check-in.'"
    "The Wildlife Strike protocol: Update the aircraft status to In Maintenance, log the operational event and maintenance log with the fixed format: 'Due to Wildlife Strike, aircraft {tail_number} grounded for maintenance, {flight_number} on {date}.'"
    "Gate Change protocol: When a flight’s gate changes, use tools create_operational_event, update_flight_status_for_date ( status: boarding-update or landing-update based on the context ), and send_user_notification. Log an event with type 'Gate Change' and details exactly: 'Gate Change for {flight_number} on {date} at {airport_code}: {old_gate}->{new_gate}' If the change causes a boarding delay, set the flight status to 'delayed-gate-change'; . Notify the airport ops channel (ops-{airport_code_lower}) with message exactly: 'Gate Change: {flight_number} {date} {old_gate}->{new_gate} at {airport_code}' No other fields may be modified by this protocol."
    "Health Risk Possibility Protocol: If there is any indication that a passenger may experience a medical emergency during the flight, they must not be allowed to board the aircraft. The reservation should be refunded immediately ( raise Refund protocol ). The incident must be reported to the operations channel (event_type: 'Health risk' ) with the exact message: 'Due to health risk possibility, passenger prevented from traveling on aircraft {flight_number}, Reservation {reservation_id}, on {date}.'"
    "Forbidden Cabin Items Advisory protocol: When a Restricted Articles found on the flight or before boarding, It should be removed from passenger’s possession, document the item removal. Log an operational event with event_type 'CABIN_ITEMS' and details exactly: 'Cabin items advisory: {item_name} removed from passenger’s possession; item secured as non-threatening.' Notify 'ops-phx' with: 'Cabin items advisory issued for {flight_number} ({date}) - {item_name} removed and secured.'"
    "Cabin Equipment replacement Protocol: When a cabin equipment is missing or damaged or needed, log an operational event with the event type 'equipment_change' and the exact message: 'Cabin equipment change needed for {flight_number} on {date}; ({equipment}).' ,send notification to to operation channel with the same message"
    "Wheelchair Shortage protocol : When there is a shortage of wheelchairs for passengers requiring mobility assistance, coordinate with ground services to source additional wheelchairs or reallocate available units.Delay boarding if needed until a wheelchair is available for each passenger who requested it.Log an operational event with event_type 'ASSISTANCE_SHORTAGE' and details exactly:'Wheelchair shortage for {flight_number} on {date}; boarding delayed {delay_minutes} minutes.' Notify 'ops-{iata}' with: 'Wheelchair shortage reported for {flight_number} ({date}); boarding delayed {delay_minutes} minutes to arrange assistance.'"
    "Wheelchair Boarding Lift Breakdown protocol: When the boarding wheelchair lift becomes inoperative, request an alternate lift from ground services immediately. Delay boarding until the lift is available to ensure safe wheelchair boarding. Log an operational event with event_type 'GROUND_EQUIPMENT' and details exactly: 'Boarding lift inoperative for {flight_number} on {date}; alternate lift requested; boarding delayed {delay_minutes} minutes.' Notify 'ops-{origin_iata}' and 'ops-{destination_iata}' with the same fixed-format messages"
    "Ramp Equipment Replacement protocol: When a baggage cart or ramp equipment fails during loading, request a replacement immediately, reroute remaining carts, prioritize transfer bags, and delay ( with 'delay' status ) boarding as needed. Log an operational event with event_type 'BAGGAGE_HANDLING' and details exactly: 'Baggage cart breakdown for {flight_number} on {date}; replacement requested; transfer bags prioritized; boarding/loading delayed {delay_minutes} minutes.'."
    "Customer Query Protocol: When answering customer queries , log the operational event with message 'Customer query answered.' and event_type CUSTOMER_COMMUNICATION"
    "Pilot In-Flight Medical Diversion protocol: When a pilot or co-pilot becomes medically unfit during flight, divert to the nearest suitable airport, coordinate ground medical assistance, and log the diversion for origin , destination and diverted airport in that order with the exact message: 'In-flight crew medical diversion for {flight_number} on {date} - landed at {nearest_airport_iata} for crew medical assistance.' ,Event type : 'Diversion'"
    "Passenger In-Flight Medical Emergency protocol: When a passenger experiences a critical health emergency during flight, provide immediate first aid, request medical assistance from onboard professionals if available, and coordinate an emergency landing at the nearest suitable airport. Log the diversion for origin, destination, and diverted airport with the exact message: 'In-flight passenger medical emergency for {flight_number} on {date} - landed at {nearest_airport_iata} for urgent medical assistance.',Event type : 'Diversion'"
    "Rodent Onboard Emergency protocol: When a rodent (e.g., mouse or rat) is sighted inside the aircraft during flight, coordinate an emergency landing at the nearest suitable airport for sanitation and maintenance inspection. If its a diversion, log the diversion for origin, destination, and diverted airport in that order with the exact message: 'In-flight rodent sighting for {flight_number} on {date} - landed at {nearest_airport_iata} for urgent maintenance and pest control.' If the closest airport is the origin, log the event at origin and destination with the the previous message and event type 'Return', and update the flight status to 'returned'. Then Initiate the Aircraft AOG protocol."
    "Maintenance Done - station authority & order: When the instruction names {airport_code} as the completion station, treat it as authoritative for logging even if aircraft location differs; use get_airport_by_code for airport_id; for multiple aircraft process sorted by aircraft_id ascending; for each: create_operational_event (event_type 'Maintenance Done', details exactly 'Maintenance Done for {tail_number} on {date} at {airport_code}', event_timestamp_utc = instruction timestamp), then set_aircraft_status 'Active'; if relocation is specified, relocate after all logs/status updates in the same ascending order; do not add extra move events unless explicitly requested."
    "Non-Medical Diversion protocol: When needed divert to the nearest suitable airport, and log the diversion for origin , destination and diverted airport in that order with the exact message: 'Diversion for {flight_number} on {date} - landed at {nearest_airport_iata}.' and update the flight status to diverted (event_type 'Diversion'). Then append an unscheduled maintenance log with event_type 'Unscheduled' with message 'Unscheduled maintenance for {tail_number} after diversion to {airport_code}.'"
    "In-flight Damaged Seat Protocol:locate the passenger’s reservation by find_reservations_by_user, Update cabin with update_reservation_details,log operational event with type: 'Cabin change' and exact message 'In-flight cabin change for {user_id}', use the same message for append_maintenance_log with event_type : 'Unscheduled' . set aircraft status to 'In Maintenance'"
    "Delay Protocol: create operational event with event_type 'Minor Delay' and update flight status for date and record the delay with delay_flight_actual_times_for_date if the delay time is provided and notify the ops channel"
    "Low Visibility Procedures (LVP) protocol: When LVP is declared at an airport, with update_flight_status_for_date set affected flights to 'delayed', and for 20 minutes with delay_flight_actual_times_for_date, log an operational event (event_type 'Minor Delay') with details 'LVP in effect; {flight_number} delayed 20 minutes.', and notify the airport's ops channel with the same message."
    "Gate Power Outage protocol: When a gate power outage occurs, with update_flight_status_for_date set affected flights separately to 'delayed' ( batch update if possible ), log the issue at the airport with create_operational_event with the exact message 'Gate power outage; {fight_numbers_coma_separated} marked delayed.' (event_type 'Technical Issue'), notify the airport's ops channel with the same message, verify with events_at_airport_on, and do not follow the standard Delay protocol."
    "DCS Outage protocol: When a Departure Control System (DCS) outage occurs, with update_flight_status_for_date set affected flights to 'delayed' and apply a fixed 20-minute delay with delay_flight_actual_times_for_date, log the issue at the impacted airport using create_operational_event (event_type 'Technical Issue') with the exact message 'BOS DCS outage; {flight_numbers_comma_separated_with_one_space_after_each_comma} marked delayed.', and notify the airport's ops channel with the same message; do not follow the standard Delay protocol (no passenger notifications required)."

    ## defaults
    "Default airport's operations channel ( ops-{airport-code-lower} )"
    "Default communication channel for the passenger of the flight is 'pass-{flight_number}-{date}'"
    "Always use the default maintenance technician id as TECH-{airport-code-upper}-01 for append_maintenance_log"
    "default delay message: 'Delay by {minutes} minutes for {flight_number} ({date}) at {airport_code}.'"

    ## maintenance routines
    'A-Check (scheduled) : Append the maintenance log first - maintenance_type: "A-Check", description: "Routine A-Check inspection.", corrective_action: "Scheduled inspection of systems and components.", technician_id: TECH-{airport_code}-01, event_timestamp_utc: {instruction_timestamp} - then set aircraft status to "In Maintenance".'
    'B-Check (scheduled) : Append the maintenance log first - maintenance_type: "B-Check", description: "Routine B-Check inspection.", corrective_action: "Detailed inspection of systems and structure.", technician_id: TECH-{airport_code}-01 (default if unspecified), event_timestamp_utc: {instruction_timestamp} - then set aircraft status to "In Maintenance".'
    'C-Check (scheduled) : Append the maintenance log first - maintenance_type: "C-Check", description: "Routine C-Check inspection.", corrective_action: "Scheduled heavy maintenance C-Check.", technician_id: TECH-{airport_code}-01 (default if unspecified), event_timestamp_utc: {instruction_timestamp} - then set aircraft status to "In Maintenance".'
    ## allowed values
    "Allowed operational event types include: Gate Change, Minor Delay, Technical Issue, Weather, Passenger Misconduct, Medical Emergency, Diversion, Security Alert, Crew Replacement, Crew Training, AIRCRAFT_AOG, Fuel Disruption, CUSTOMER_COMMUNICATION, SCHEDULE_CHANGE, ANALYSIS, REFUND,CABIN_ITEMS, Manifest audit, Delayed - Gate Change, Health risk, Cabin change, equipment_change, Review, Return , Maintenance Done, AIRCRAFT_MOVED, Compliance audit, Crew shortage, UNATTENDED_BAGGAGE,ASSISTANCE_SHORTAGE,GROUND_EQUIPMENT,BAGGAGE_HANDLING",
    "Allowed crew status: Active, On Leave, Inactive, Sick Leave, Training",
    "Allowed crew roles: Captain, First Officer, Flight Attendant",
    "Allowed maintenance types: Unscheduled, A-Check, B-Check ,C-Check , Component Replacement, Avionics, Avionics Update, Tire Replacement, Hydraulic System Check, Cabin System Repair, Flight Controls,"
    "Allowed flight status: landed, canceled, available, delayed, flying ,on time, diverted, baggage delay,returned,boarding-update,delayed-gate-change,landing-update,security-hold"
    "Allowed aircraft status: Active, In Maintenance, Stored"
    #
    "When no policy exists, follow the verb order in the instructions as the canonical ordering"

]
