WIKI = """
"All tasks must be completed successfully utilizing solely the supplied GitHub MCP tools.",
    "Every tool call must utilize parameters that are valid and are present either in the task instruction or in outputs from previous tools.",
    "Task execution should proceed according to a logical workflow, beginning with authentication and continuing through to completion.",
    "The deliverables produced by tasks must match exactly those detailed in the instruction.",
    "The initial step requires authentication via get_me, utilizing a valid username and auth_key.",
    "Authentication tokens are required to adhere to the GitHub format and must be valid for the designated user.",
    "For authentication to succeed, the username must correspond to the owner of the token.",
    "Valid repository names and owners are required for all repository operations.",
    "When creating a repository, the parameters name, description, private/public, and autoInit must be provided appropriately.",
    "Before deleting a repository, its existence must be verified.",
    "In cases of repository naming conflicts, the system should resolve them by adding the '_v2' suffix. If a new repository is created with a name that already exists, the resulting repository name must be 'original_name_v2'.",
    "All file operations are required to utilize valid file paths that are relative to the root of the repository.",
    "The content of files must be accurately formatted and syntactically valid according to the specific file type.",
    "Before performing file operations on branches, the system must confirm that the branch exists.",
    "Commit messages are required to be descriptive and adhere to the conventional commit format.",
    "When creating a branch, a valid commit SHA from the outputs of list_commits must be used.",
    "Standard patterns (such as feature/, bugfix/, etc.) must be used for branch names.",
    "Valid source and target branches are required when creating a pull request.",
    "Instruction specifications must be matched by pull request titles and descriptions.",
    "Required fields (title, body, labels, assignees) must be provided when creating an issue.",
    "The issue numbers returned by create_issue must be recorded for use in later operations.",
    "Updates to issues must alter only the designated fields (title, body, labels, assignees).",
    "The exact text provided in the instruction must be included in issue comments.",
    "Valid PR numbers obtained from create_pull_request returns must be used for all pull request operations.",
    "Pull request reviews are required to have the correct body text and state.",
    "Valid merge methods (squash, merge, rebase) are required when merging pull requests.",
    "The status checks for pull requests must confirm that the PR is in the appropriate state.",
    "Code search queries are required to be both specific and directly related to the task objective.",
    "The security scanning process is required to verify the presence of real vulnerabilities within the designated repository.",
    "Code scanning alerts are to be accurately classified and thoroughly documented.",
    "Execution of tasks must adhere to the logical order of dependencies among tool calls.",
    "Only items that have been created or modified should be verified during verification steps.",
    "Tasks should exclude any superfluous tool calls that do not pertain to the deliverable.",
    "In multi-step workflows, parameters for subsequent steps must be obtained from the outputs of previous tool executions.",
    "The outputs of the task are required to correspond precisely to the values detailed in the instruction.",
    "Every required deliverable must be generated and validated successfully.",
    "Completion of the task must be validated by executing the relevant verification procedures.",
    "Data collection should be limited strictly to what is necessary to achieve the task goal.",
    "Tasks are required to manage possible errors gracefully, such as when a repository or file cannot be found.",
    "Tasks must avoid using hardcoded values that are not present within the system.",
    "Tasks are required to deny operations that cannot be accomplished using the available tools.",
    "Tasks are required to return informative error messages whenever operations do not succeed.",
    "Task execution must adhere precisely to the deliverable outlined in the instruction.",
    "Every action parameter should be directly linked to the instruction text.",
    "Instructions are required to focus on the intended goal rather than providing detailed procedural steps.",
    "The complexity of the task must align with the designated difficulty level (Hard/Expert).",
    "Tasks should reflect authentic GitHub workflows that developers are likely to execute in practice.",
    "Tool usage should illustrate familiarity with genuine GitHub API patterns.",
    "Workflows should maintain efficiency and refrain from collecting superfluous data.",
    "Task scenarios should be realistic and applicable to actual development workflows.",
    "Code implementations are required to adhere to established programming standards.",
    "Documentation updates need to be substantive and organized in a clear manner.",
    "Industry standards must be adhered to for security practices.",
    "Accessibility considerations must be incorporated into all UI/UX improvements.",
    "Unless stated otherwise, the default state for list_issues and list_pull_requests operations is 'open'.",
    "Unless explicitly stated otherwise, the 'main' branch serves as the default branch for all repository operations.",
    "Parameters such as 'open' and 'main' are automatically accessible for tool invocations.",
    "If instructions mention 'most recent issue', 'latest issue', or 'existing issues', the agent is required to identify the corresponding issue numbers by exploring the repository.",
    "Unless directed otherwise by the instruction, open issues must be prioritized during issue discovery.",
    "If there are several issues, 'most recent' denotes the issue with the largest issue number within the repository.",
    "Issue selection should rely on issue state, labels, or creation date, according to what is specified in the instruction.",
    "The agent must refrain from presuming particular issue numbers until it has identified the issues present in the repository.",
    "Prior to establishing new repositories, the agent needs to review current repositories to discern naming conventions and the set of available labels.",
    "Workflows for creating repositories are required to analyze related existing repositories to guide the configuration of new repositories.",
    "Before assigning labels to new repositories, the agent must identify available labels from the current repositories.",
    "Prior to creating a repository, the agent must verify for naming conflicts by inspecting the existing repositories.",
    "If any pull request checks are either pending or have failed, the agent must display the message 'Pull request cannot be merged: required checks are still pending. All checks must pass before merging.' and terminate the merge workflow.",
    "Before initiating a merge, pull request merge workflows must ensure that all required checks have passed.",
    "Status verification must be incorporated as a prerequisite for merging within pull request review workflows.",
"""
