RULES = [
    "The 'post-game' analysis workflow is permitted to execute solely for games where games.game_status equals 'Final'. Any tools generating post-game reports must strictly enforce this condition.",
    "High-leverage applies when leverage_index exceeds 1.5. All in-game auto-bookmarking and post-game 'high leverage' analyses must apply this strict greater-than threshold as a filter.",
    "For series queries, to determine the next scheduled game, select the game with the earliest games.game_date that is greater than or equal to current_date and has game_status equal to 'Scheduled'. If several games occur on that earliest date, pick the one with the lowest game_pk. The current_date parameter must always be provided explicitly; implicit use of 'today' is not permitted.",
    "Trend flags require at least 50 pitches, or at least 30 swings, or at least 25 batted balls before a slice can be displayed.",
    "Before flagging trends, use empirical-Bayes (EB) shrinkage to stabilize short-window rates toward the season baseline.",
    "Address multiplicity by applying False Discovery Rate (FDR) and practical-effect thresholds; retain only those flags that are statistically meaningful.",
    "Execute trend filtering exclusively with the designated tool(s) and store a deterministic flags table associated with the applied thresholds.",
    "Before calculating mix/usage or spatial statistics, all pitch-type labels must be aligned to the canonical schema (for example, vendor 'Sweeper' mapped to 'SW', 'Sinker' to 'SI').",
    "Prior to generating zone-based statistics or heatmaps, spatial pitch and miss locations are required to be normalized onto a 12x12 grid from the catcher’s perspective, ensuring that the grid bounds are valid (maximum is greater than minimum).",
    "Pitch execution grades must be strictly selected from ['Executed', 'Minor miss', 'Major miss'] and must be deterministically assigned based on either miss_distance_inches or quadrant deviation.",
    "Execution threshold policy: Execute when miss_distance_inches is less than or equal to 3.0; classify as Minor miss when miss_distance_inches is greater than 3.0 but less than or equal to 9.0; classify as Major miss when miss_distance_inches exceeds 9.0.",
    "Automatic in-game bookmarks require leverage_index greater than 1.5 and must include a short narration; is_manual_alert must be set to false for these bookmarks.",
    "Manual alerts must have is_manual_alert set to true and may be generated at any time, without any leverage_index restriction.",
    "Acceptable values for draft_status in game_day_events are 'draft', 'published', and 'archived'. All changes between these states require explicit action and must be logged in the audit log.",
    "Every 'post-game' scouting report is required to contain a core_narrative_text and a gslides_link, and must also have curated video_playlists attached that are associated with the report_id.",
    "While compiling opponent/player insights for any report, give precedence to high-leverage patterns and merge any repetitive bullets into one actionable directive.",
    "Curated insight text should be generated strictly from deterministic templates, not free-form sentences, following the format: '{category}_{metric}_{bucket}', where category is one of {tendency, execution, stamina, situational, predictability}.",
    "If more than N insights qualify for display, order them first by supporting_stat_value in descending order, and use player_id in ascending order as a stable tie-breaker.",
    "For lists of 'next series probable pitchers', arrange pitchers in ascending order by full_name to ensure consistent presentation.",
    "Weekly development reports are generated based on the team off-day schedule; by default, players whose roster_status matches 'IL%' or 'Taxi' are excluded from the active roster snapshot unless they are specifically opted in.",
    "Every new player development report must include exactly two video playlists: 'Positive Reinforcement' containing 3–5 clips, and 'Teaching Moments' containing 2–3 clips. Tools are required to enforce these clip count ranges whenever these playlist names are used.",
    "All tool arguments must be clearly specified within the instruction or deterministically obtained from previous tool outputs or established rules; dates and IDs must not rely on hidden defaults or implicit clocks.",
    "New rows must assign IDs as consecutive integers, calculated as max(existing_id)+1 for each table (such as report_id, playlist_id, goal_id, run_id, ingestion_id, grade_id). Paths and links (for example, S3 paths using player_id and week_of_date) must be generated deterministically from the provided inputs.",
    "Each workflow_runs record is required to contain dag_name, game_pk (if relevant), status, start_time_utc, end_time_utc, and a log_s3_path that is deterministically derived.",
    "Any tool relying on tables that are not present must return a structured error explicitly listing the missing table(s), and must not generate or simulate any results.",
    "If the schema includes multiple overlapping sources (such as event log and box score), record a single source of truth decision in workflow_runs and continue only once a QC pass has been completed.",
]
