RULES = [
    "When fulfilling an order for a single item, you must allocate inventory from the warehouse that holds the highest 'quantity_available' for the requested SKU.",
    "When multiple warehouses meet an order's specified criteria (e.g., certifications), you MUST fulfill the order from the warehouse holding the highest 'quantity_available' of the requested SKU. If the required quantity is not available in any single warehouse, the task cannot be completed.",
    "If a single warehouse cannot fulfill the entire quantity of an order line, as much as possible must be fulfilled from the warehouse with the largest inventory. The remaining quantity must then be fulfilled from the warehouse with the second-largest inventory. This process should continue until the order is completely fulfilled. Separate outbound orders must be created for each warehouse shipment."
    "For any outbound order with a priority of 'Critical', an 'Air' carrier must be used. From the eligible air carriers, you MUST select the one with the highest 'on_time_delivery_percentage'. If a tie exists, the carrier with the highest 'average_rating' must be chosen as the tie-breaker."
    "When executing a stock transfer, the source warehouse MUST be the one with the highest 'quantity_available' of the specified SKU, to minimize disruption to its operations."
    "A carrier is considered to be underperforming if their 'on_time_delivery_percentage' is below 95%.",
    "When reassigning an order from an underperforming carrier, the new carrier MUST support the same mode of transport and have the highest 'on_time_delivery_percentage' among the available alternatives.",
    "When creating a replacement purchase order for damaged goods received from a supplier, the new order must be sent to the original supplier and must be marked with 'High' priority to ensure expedited processing.",
    "All new Purchase Order numbers MUST be generated by finding the highest existing PO number in the format 'PO-YYYY-XXXX' for the current year and incrementing the sequential part ('XXXX') by one. The year ('YYYY') should reflect the year the order is created. The sequential number restarts from '0001' each year.",
    "All products returned by a customer must be shipped back to the warehouse from which the original order was dispatched.",
    "For all domestic returns weighing less than 500kg, the designated return carrier is 'UPS' with the service level 'Ground - Return Service'.",
    "A credit memo ID must be generated for all approved returns. The ID format must be 'CM-' followed by the numeric part of the original Order ID (e.g., 'CM-0001' for 'ORD-0001').",
    "For any outbound order with a priority of 'High', a carrier with the highest 'on_time_delivery_percentage' that supports the required mode of transport must be used. If a tie exists, the carrier with the highest 'average_rating' must be chosen as the tie-breaker.",
    "All new Return Merchandise Authorization (RMA) numbers MUST be generated sequentially. If no RMAs exist, the first ID must be 'RMA-1001'. Otherwise, the ID is generated by finding the highest existing RMA number in the format 'RMA-XXXX' and incrementing the sequential part ('XXXX') by one.",
    "When an action pertains to multiple subjects, any corresponding ID parameter must be a single string with the individual IDs joined by a semicolon (';') with no spaces.",
    "For all international returns, the designated return carrier is 'DHL Express'.",
    "For all orders for customer 'Kappa Books Pvt Ltd.', the designated carrier is 'Hanjin'.",
    "For 'Medium' or 'Low' priority orders, if no other rule applies, select the active carrier with the highest 'average_rating' for the required transport mode. If tied, select the one with the highest 'on_time_delivery_percentage'.",
    "All products in the 'Technology' category with a 'unit_cost' greater than $10,000 must be stored in a warehouse with 'High-Value Cage' and 'UL Certified Vault' capabilities.",
    "To return undamaged items to available inventory, the 'update_inventory_damage_status' tool must be used with a negative number for the 'damaged_quantity', representing a reversal of damage or a positive return to stock.",
    "For all orders for customer 'Epsilon Fashion Co.', the recognized revenue for each unit of 'Organic Cotton T-Shirt' is fixed at $25.00 USD."
    "When comparing carrier profitability, if two carriers result in an identical profit, the one with the higher 'on_time_delivery_percentage' shall be considered the superior choice. If a tie still exists, the one with the higher 'average_rating' must be chosen.",
    "All 'Sea' shipments to South Korea must use the designated carrier 'Hanjin'.",
    "All new Sales Order numbers must be generated in the format 'SO-YYYY-XXXX', where 'YYYY' is the current year and the sequential number 'XXXX' must match the number from the corresponding Order ID (ORD-XXXX)."
]
