RULES = [
    "Prior to initiating a sprint, confirm the team’s capacity and make sure that the total planned story points do not surpass 80% of the team’s average velocity calculated from the previous 2 completed sprints. For teams lacking velocity history, restrict sprint capacity to 20 story points per team member.",
    "Tasks that have unresolved dependencies are not permitted to transition to 'in_progress' status. Before changing any task status to 'in_progress', verify that all tasks it depends on are marked as 'done'. If a task is blocked by dependencies, its blocked_by field must be updated accordingly.",
    "No single team member may be assigned more than 25 story points in any active sprint. When allocating tasks, review the employee’s current sprint workload and redistribute assignments if this threshold would be exceeded.",
    "Sprints are required to progress through statuses in the following order: planning, then active, then completed. Each team may have no more than one sprint in 'active' status simultaneously.",
    "For sprints in active status, burndown must be calculated each day. Should the completion percentage drop more than 20% below the expected linear progress, blocked tasks must be identified and either re-planning or escalation should be considered.",
    "Tasks marked as critical priority are to be assigned to senior team members (proficiency level 4 or higher), except when no senior members are available. No task may be reassigned more than two times per sprint unless management grants approval.",
    "A retrospective must be created within 2 days after each sprint is completed. Each retrospective is required to contain at least one entry for both 'what went well' and 'what needs improvement'. Any action items identified in retrospectives must be transformed into tasks for inclusion in the subsequent sprint.",
    "For all tasks with a status of 'in_progress' or 'done', time must be logged at intervals no greater than every 2 days. Tasks in the 'done' status must have logged hours totaling at least 50% of their estimated story points, using the conversion rate of 1 story point to 2 hours.",
    "After a sprint transitions to 'active' status, additional tasks may only be added if they are of critical priority, if an equivalent number of story points are removed, or if team velocity permits and all team members consent. Every change to scope must be recorded in the task history.",
]
