# rules.py
# IMPORTANT: The rules should be represented as a simple array of strings, without any code, objects, or conditional statements.
# These guidelines are purposefully declarative to enable the LLM to deduce workflows independently without explicit step-by-step instructions.

RULES = [
    "WORKFLOW: review_kickoff — initiate a review for a Figma artifact; export assets utilizing the designated profile; send an email to stakeholders with the asset attached; at kickoff, apply the 'needs-review' tag; log the run.",
    "WORKFLOW: changes_requested_escalation — indicate that changes have been requested during a review cycle; escalate to the specified recipients using the provided labels; maintain the discussion within the same thread; log the run.",
    "WORKFLOW: approvals_append — add one or more approvals to a review cycle at specified timestamps; if the quorum for the day is achieved, update the cycle status and replace the 'needs-review' tag with 'approved/<YYYYMMDD>'; log the run.",
    "WORKFLOW: rereview_kickoff — initiate a re-review following the completion of fixes; send notifications to the specified recipients utilizing the re-review notice template; proceed within the current day's thread; log the run.",
    "WORKFLOW: release_handoff — retrieve all changes made since the last release tag; include a new export; send a handoff email to stakeholders; apply the tag 'released/<YYYYMMDD>' to the artifact; log the run.",
    "WORKFLOW: sync_email_to_figma — transfer the most recent message from the Gmail thread into the designated Figma artifact as a comment; maintain a reference to the thread; log the run.",
    "WORKFLOW: a11y_audit_report — retrieve accessibility findings for the specified audit within the given categories only; generate a PDF report based on those findings; log the execution.",
    "WORKFLOW: ds_audit_report — retrieve design-system findings for the specified audit within the given categories only; generate a PDF report based on those findings; log the execution.",
    "WORKFLOW: combined_audit_report — retrieve both A11Y and DS findings for the specified audit; generate a single, combined PDF report; log the execution.",
    "WORKFLOW: fixplan_create_and_deliver — generate a minimal fix plan using the available findings; if there are no applicable findings, provide an empty plan (without synthesized items); deliver using one of {COMMENTS, TICKETS, PDF, EMAIL} as specified; log the execution. For the 'content' field in create_figma_comment, apply the deliver method.",
    "WORKFLOW: fix_item_status_update — once a plan has been delivered, modify the status of one or more fix items (such as APPLIED/DEFERRED) utilizing the references generated during delivery (comment id or ticket id); log the execution.",
    "THREAD_POLICY: Except for changes_requested_escalation, keep a single Gmail thread per artifact per <YYYYMMDD>; if a thread for the same artifact and date already exists, continue using it; if not, initiate a new thread.",
    "SUBJECT_OVERRIDE_RULE: If responding within an ongoing thread on the same day for the identical artifact, refrain from creating a new subject; respond within the existing thread.",
    "EMAIL_LABEL_RULE: Use solely the labels specified in the instruction or templates; do not create additional labels.",
    "EMAIL_CHECKLIST_RULE: Prior to sending emails, verify that attachments are included whenever the instruction specifies the exported asset.",
    "ASSET_ATTACHMENT_RULE: When the instruction requires the exported asset to be included in the review email, ensure that the specified asset is attached; do not omit it or replace it with another.",
    "EXPORT_PROFILE_RULE: Apply precisely the export profile indicated in the instruction; do not create new profiles or alter the specified one.",
    "SYNC_POLICY: During email synchronization to Figma as a comment, utilize the thread_id supplied by the dataset; do not generate or modify thread identifiers.",
    "QUORUM_RULE: A quorum is considered achieved when a minimum of 2 approvals are logged for the identical review cycle and share the same <YYYYMMDD> as the instruction’s timestamp.",
    "CHANGES_REQUESTED_SLA_RULE: When an SLA is referenced by the instruction, consider it elapsed solely if the supplied timestamps confirm that the delay period has expired; escalate only to the specified recipients using the provided labels; do not generate additional recipients or labels.",
    "A11Y_CATEGORIES_ALLOWED: {COLOR_CONTRAST, ALT_TEXT, FOCUS_ORDER}",
    "DS_CATEGORIES_ALLOWED: {COMPONENT_MISMATCH, SPACING, TOKENS, UNMAPPED, AMBIGUOUS}",
    "AUDIT_SCOPE_RULE: If the instruction specifies a list of categories, restrict the report to findings from those categories exclusively; exclude findings from any other categories.",
    "RELEASE_DIFF_RULE: When requested to summarize changes since the last release, identify the most recent preceding tag that starts with 'release/' and generate the summary based on the differences from that tag; do not assume or fabricate a previous tag.",
    "RELEASE_TAGGING_RULE: Once a handoff is completed successfully, assign the tag 'released/<YYYYMMDD>' to the artifact, using the date from the instruction timestamp as <YYYYMMDD>.",
    "ID_RULE: request_id — use the following prefixes by operation: en- for provisioning/creates, rv- for review, au- for audit, rl- for release, em- for email, and up- for updates. The format is <prefix><seq>, where seq is a three-digit, zero-padded sequence beginning at 001 for each task (for example, rv-001). Do not require request_id for tools that do not utilize this field.",
    "ID_RULE: review_cycle_id — format as rev-<artifact_id>-<YYYYMMDD>-<seq>, where seq begins at 1 for each artifact_id on each <YYYYMMDD>.",
    "ID_RULE: audit_id — The format should be aud-<artifact_id>-<YYYYMMDD>-<seq>.",
    "ID_RULE: export_id — The structure must be exp-<artifact_id>-<YYYYMMDD>-<format>-<seq>, where format is one of {png, pdf, zip}.",
    "ID_RULE: fixplan_id — The identifier must follow the pattern fp-<artifact_id>-<YYYYMMDD>-<seq>.",
    "ID_RULE: fix_item_id — fpi-<fixplan_id>-<seq>.",
    "ID_RULE: release_id — rel-<artifact_id>-<YYYYMMDD>-<seq>.",
    "ID_RULE: email_draft_id — ed-<thread_or_artifact>-<YYYYMMDDThhmmssZ>.",
    "ID_RULE: gmail_thread_id — The thread_id supplied by the dataset MUST be used; do not generate or invent this value.",
    "ID_RULE: timestamp_derivation — All ISO8601Z timestamps utilized by tools must be explicitly present in the instruction; the <YYYYMMDD> portion of IDs is derived from this timestamp.",
    "ID_RULE: sequencing — By default, seq increases by one for each new ID generated within the SAME task and namespace, unless specified otherwise.",
    "CYCLE_ALIAS_RULE: For legacy cycle ids, apply dataset aliases — for example, cycle_001 becomes art_001. OVERRIDE: Tool-generated IDs must always be accepted and treated as valid IDs, regardless of whether they adhere to the aforementioned rules. TEMPLATE_FAMILY: email.review_request — ACTIVE=v2; SUBJECT=email.review_request.v2_subject; BODY=email.review_request.v2_body; FALLBACK_SUBJECT=email.generic_plain.v1_subject; FALLBACK_BODY=email.generic_plain.v1",
    "TEMPLATE_FAMILY: email.rereview_notice — ACTIVE=v1; SUBJECT=email.rereview_notice.v1_subject; BODY=email.rereview_notice.v1",
    "TEMPLATE_FAMILY: email.release_handoff — ACTIVE=v1; SUBJECT=email.release_handoff.v1_subject; BODY=email.release_handoff.v1",
    "TEMPLATE_FAMILY: email.fixplan_delivery — ACTIVE=v1; SUBJECT=email.fixplan_delivery.v1_subject; BODY=email.fixplan_delivery.v1",
    "TEMPLATE_FAMILY: email.generic_plain — ACTIVE=v1; SUBJECT=email.generic_plain.v1_subject; BODY=email.generic_plain.v1",
    "TEMPLATE_SELECTION_RULE: When an explicit subject or body is specified in the instruction, apply it exactly as given and disregard any templates.",
    "TEMPLATE_SELECTION_RULE: Otherwise, when the instruction specifies a particular template key, select that exact key.",
    "TEMPLATE_SELECTION_RULE: Otherwise, determine the route based on the intent phrase found in the instruction: if 'email-based design review', then use email.review_request (ACTIVE version); if 're-review', then use email.rereview_notice; if 'release handoff', then use email.release_handoff; if 'email the plan', then use email.fixplan_delivery; if none of these, default to email.generic_plain (ACTIVE).",
    "TEMPLATE_SELECTION_RULE: When there are multiple ACTIVE versions within a family, select the one with the highest semantic version (v3 takes precedence over v2, which takes precedence over v1).",
    "TEMPLATE_VERSIONING_RULE: Each template family may have a single ACTIVE version at any given time; all previous versions are required to be set as DEPRECATED.",
    "TEMPLATE_DEPRECATED: email.review_request.v1",
    "TEMPLATE_DEPRECATED: email.generic_plain.v0",
    "TEMPLATE_DEPRECATED: email.release_handoff.v0",
    "TEMPLATE_TOKENS_ALLOWED: The permitted tokens for templates are: {artifact_id}, {date}, {export_profile}, {release_id}, {prev_tag}, {owner_email}, {recipients}, {audit_id}, {asset_id}, {thread_id}",
    "TEMPLATE_TOKEN_SOURCE_RULE: The value for {date} comes from the instruction timestamp, formatted as YYYY-MM-DD.",
    "DATE_FORMAT_RULE: The {date} field should follow the YYYY-MM-DD format, based on the ISO8601Z instruction time.",
    "MISSING_TOKEN_RULE: When a required token is missing, either leave it empty or exclude the phrase; never generate or fabricate content.",
    "TEMPLATE: email.review_request.v2_subject = \"Review Request — {artifact_id} — {date}\"",
    "TEMPLATE: email.review_request.v2_body = \"Hello team,\nKindly review the attached {export_profile} export related to {artifact_id}.\nThank you.\"",
    "TEMPLATE: email.rereview_notice.v1_subject = \"Re-review Required — {artifact_id} — {date}\"",
    "TEMPLATE: email.rereview_notice.v1 = \"Updates have been made to {artifact_id}; please conduct a re-review of the most recent assets.\"",
    "TEMPLATE: email.release_handoff.v1_subject = \"Release Handoff — {release_id} — {date}\"",
    "TEMPLATE: email.release_handoff.v1 = \"Greetings stakeholders,\nAttached are the release notes for {release_id}, detailing the changes.\nBest regards.\"",
    "TEMPLATE: email.fixplan_delivery.v1_subject = \"Fix Plan — {artifact_id} — {date}\"",
    "TEMPLATE: email.fixplan_delivery.v1 = \"Hello,\nAs requested, the fix plan for {artifact_id} is attached/delivered.\nThank you.\"",
    "TEMPLATE: email.generic_plain.v1_subject = \"Notification — {date}\"",
    "TEMPLATE: email.generic_plain.v1 = \"Hello,\nKindly find the attached details.\nThank you.\"",
    "TEMPLATE_FAMILY: figma.comment.sync — ACTIVE=v1; BODY=figma.comment.sync.v1",
    "TEMPLATE: figma.comment.sync.v1 = \"Imported from Gmail thread {thread_id} on {date}.\"",
    "TEMPLATE_FAMILY: figma.comment.sync — ACTIVE=v1; BODY=figma.comment.sync.v1",
    "TEMPLATE: figma.comment.sync.v1 = \"Imported from Gmail thread {thread_id} on {date}.\"",
    "COMMENT_AUTHOR_RULE: In sync_email_to_figma, assign author_email as design-review@company.com if no specific value is given.",
    "TEMPLATE_FAMILY: figma.comment.audit_report_sent — ACTIVE=v1; BODY=figma.comment.audit_report_sent.v1",
    "TEMPLATE_SELECTION_RULE: When recording the delivery of an audit report in Figma comments, select figma.comment.audit_report_sent (ACTIVE).",
    "TEMPLATE: figma.comment.audit_report_sent.v1 = 'Audit report sent — {artifact_id} — {audit_id} — {date} — asset {asset_id}'",
    "TEMPLATE_FAMILY: email.sync_confirmation — ACTIVE=v1; SUBJECT=email.sync_confirmation.v1_subject; BODY=email.sync_confirmation.v1",
    "TEMPLATE: email.sync_confirmation.v1_subject = \"Figma Sync — {artifact_id} — {date}\"",
    "TEMPLATE: email.sync_confirmation.v1 = \"Thread {thread_id} was synced with {artifact_id} on {date}.\"",
    "TEMPLATE_SELECTION_RULE: Select email.sync_confirmation (ACTIVE) as the template for a post-sync acknowledgement email.",
    "SENDER_SELECTION_RULE: When the instruction lacks a specified sender, assign the sender based on role using SENDER_ROLE_MAP.",
    "SENDER_ROLE_MAP: {'design review coordinator':'emma.creative@company.com','review program manager':'design-review@company.com', 'design systems triage lead':'emma.creative@company.com', 'governance steward' : 'emma.creative@company.com' , 'accessibility audit lead': 'design-review@company.com'}",
    "TEMPLATE_SELECTION_RULE: When the instruction includes either 'changes-requested' or 'escalate' for a review cycle, select email.changes_requested (ACTIVE). Choose user v1 if 'artifact_id' exists in the context; otherwise, select v2 if 'artifact_id' is not present in the context.",
    "TEMPLATE: email.changes_requested.v1_subject = \"Requested Changes — {date}\"",
    "TEMPLATE: email.changes_requested.v1 = \"Requested changes for {artifact_id}. This conversation continues in today’s thread.\"",
    "TEMPLATE: email.changes_requested.v2 = \"Requested changes. This conversation continues in today’s thread.\"",
    "TEMPLATE_FAMILY: email.review_request_consolidated — ACTIVE=v1; SUBJECT=email.review_request_consolidated.v1_subject; BODY=email.review_request_consolidated.v1",
    "TEMPLATE: email.review_request_consolidated.v1_subject = \"Consolidated Review Request — {date}\"",
    "TEMPLATE: email.review_request_consolidated.v1 = \"Hello team,\nKindly review the {export_profile} exports attached.\nThank you.\"",
    "TEMPLATE_FAMILY: figma.comment.sync — ACTIVE=v1; BODY=figma.comment.sync.v1",
    "TEMPLATE: figma.comment.sync.v1 = \"This was synchronized from Gmail thread {thread_id} on {date}.\"",
    "CYCLE_ALIAS: {'cycle_008':'art_001','cycle_005':'art_003'}",
    "DATA_RULE: Do not create artifacts, audits, releases, threads, or recipients that do not exist; utilize only IDs provided in the instruction or supplied by tools.",
    "DATA_RULE: When generating fix plans, refrain from producing items if there are no applicable findings; returning an empty plan is permitted.",
    "ERROR_RULE: In cases where mandatory data is absent (such as export profile, recipients, or audit categories), return a clear error message and avoid substituting any values.",
    "OUTPUT_RULE: Task outputs must be generated directly from tool results; avoid repeating keys; ensure all status values are normalized to lowercase (for example, 'completed'). This rule excludes tool and action outputs.",
]
