RULES = [
    "You operate in the Retail domain and must follow auditable procedures.",
    "All write operations must be deterministic given the same inputs. Do not create random values.",
    "Idempotency: when a tool supports upsert semantics (e.g., payments by 'transaction_id', refunds by 'refund_id', supply orders by 'supply_order_id'), multiple identical calls MUST NOT create duplicates; they must overwrite the same record.",
    "Do not invent identifiers. All identifiers (order_id, tracking_id, transaction_id, refund_id, supply_order_id) must be provided by the instruction or derived from provided seeds using the designated tool (e.g., allocate_tracking_id).",
    "Order statuses are informational and must be set only via the update tool; updating status MUST NOT mutate payments, items, or fulfillments.",
    "When adding a payment, use the exact 'transaction_id' supplied and do not create any side effects beyond appending/upserting the payment entry.",
    "When issuing a refund, use the exact 'refund_id' supplied and do not remove or alter prior payments.",
    "Cancelling order items affects ONLY the specified 'item_ids' and MUST record the 'reason_code' verbatim.",
    "When editing an item's option, change only the provided option key; do not rewrite other options on that item.",
    "When tagging an order, never duplicate an existing tag value on the same order.",
    "Fraud marks are audit metadata only (risk_level, reason_code) and do not change order status or payments.",
    "A fulfillment maps a specific set of 'item_ids' to one tracking_id; do not split or merge unless explicitly instructed.",
    "Never add an identical (tracking_id, item_ids) pair to fulfillments more than once. Treat this as idempotent.",
    "When creating a new tracking ID, use 'allocate_tracking_id' with the provided courier_id and seed; do not invent formatting beyond the tool output.",
    "All tracking timeline updates must set the provided event key to the provided ISO timestamp verbatim.",
    "Use 'upsert_tracking_address' only to replace the address object associated to that tracking record; do not alter unrelated fields.",
    "Courier reassignment on a tracking record is permitted only via 'reassign_courier_for_tracking'.",
    "Price and availability changes apply strictly to the targeted 'item_id' (variant), not to sibling variants or parent products.",
    "Search queries must not be used to infer IDs; use them only to shortlist options, then operate with explicit IDs from the task context.",
    "Supply orders must be created or updated only against their explicit 'supply_order_id'. Re-issuing the same ID overwrites fields.",
    "Supply order status updates must not alter quantities or costs; status-only change.",
    "User addresses must be replaced exactly with the provided object; do not merge with existing keys.",
    "Payment methods attached to users must include a caller-provided 'id' and are stored or overwritten under that id.",
    "Computed values (e.g., totals) must follow each tool's documented behavior. Do not include taxes/discounts unless explicitly part of the tool.",
    "If multiple equally valid choices exist and no rule or instruction breaks the tie, select the lexicographically smallest identifier.",
    "When an instruction asks to report multiple identifiers in a single output, join them with a semicolon (';') with no spaces.",
    "These rules override any conflicting user phrasing in a task; tasks must remain auditable.",
]
