RULES = [
    "Create-style events must utilize a fixed created timestamp, while update-style events must utilize a fixed updated timestamp.",
    "Approvals must apply a fixed approval timestamp; however, if the review was escalated, a fixed escalated-approval timestamp must be used instead.",
    "SLA deadlines and escalation moments must be captured with fixed, deterministic timestamps.",
    "Assign each newly created row within any entity (artifacts, assets, cycles, threads, messages, comments, approvals, releases, diffs) a monotonic, human-readable identifier that is based on the present database size.",
    "The process for generating identifiers must yield the same result on every run; do not incorporate randomness or wall-clock timestamps.",
    "When multiple rows are returned, ensure the output is consistently ordered by the entity’s identifier in ascending sequence.",
    "Thread message histories must be sorted first by sent time, followed by identifier, to guarantee consistent playback.",
    "Artifacts record type, naming, ownership, location, and link metadata; fields specific to frames are filled in solely when relevant.",
    "Artifact tags are initialized as an empty list and must not change unless they are deliberately updated.",
    "Assets are connected to artifacts, log export profile and size, and initially assume a clean data-loss-prevention status with no additional details.",
    "During asset listing or grouping, maintain deterministic ordering and restrict inclusion to rows that correspond to the specified artifact linkage.",
    "New review cycles start in-flight, monitor SLA deadlines, and unambiguously capture escalation state.",
    "Updates to a cycle can modify status, thread linkage, and escalation information; assigning an escalation automatically sets the SLA breach flag.",
    "Retrieving a cycle requires an exact match: the operation yields either the one matching cycle or a deterministic not-found result.",
    "Any approval action must set the parent cycle to the approved state.",
    "When a cycle is flagged as breached, its approval timestamp indicates the escalated timeline.",
    "Approvals are added to the ledger in a deterministic sequence and do not alter the historical order retroactively.",
    "New threads define sender identity, recipients, labels, and the initial message content; the text is deterministically generated from the HTML.",
    "Any following message must have sender authorization associated with the thread’s participants; if not authorized, the system returns a uniform error.",
    "When a post is made in a thread, the thread’s updated time is refreshed according to the fixed update policy, while the ordered history remains intact.",
    "Notifications sent to a thread adopt the thread’s sender identity and utilize identical HTML-to-text normalization procedures.",
    "Comments are attached to artifacts, record the author and content, may optionally reference a source message, and include a flag indicating whether they are resolved.",
    "Comment entries are unchangeable records except for the explicit ability to update the resolution state in subsequent modifications.",
    "Releases represent versioned milestones that record the time of creation and may optionally be linked to a communication.",
    "Release diffs record items that have been added, updated, or removed, as well as highlights and version bumps, within deterministic lists.",
    "Retrieving a diff by release returns precisely one row or a deterministic not-found outcome.",
    "Before/after comparisons retain all previous items unless they are explicitly removed, and incorporate any items that are new or have been updated.",
    "Sorted lists are used for comparison outputs to guarantee consistent and repeatable results.",
    "Each change in user-visible state results in appending a terminal log entry that includes the fixed timestamp and a brief, human-readable message.",
    "Log storage maintains a one-to-one correspondence between printed timestamps and messages for auditability, applying a uniform rendering format.",
    "When creating events such as artifacts, assets, cycles, threads, releases, or diffs, always apply the fixed created time; for updates—including messages, cycle changes, or approvals—use the fixed updated or approval time as relevant.",
    "All behaviors must ensure reproducibility, maintain idempotency for repeated operations, and provide explicit failure modes in cases of invalid lookups or insufficient permissions. Every instance of the now date defaults to '2024-08-23T12:00:00Z'. To retrieve any feedback for the artifact, the default tag must contain 'needs-review'.",
    "The input parameters require that 'frame' be represented as 'FRAME'.",
    "To submit an approval request, an artifact must first be transformed into an asset by generating a new asset.",
    "The default storage_ref location follows the format 'gs://company-assets/figma-exports/<filename>'.",
    "Unless otherwise specified, the default size for a newly created PNG 2x is 2000, for PNG 3x is 3000, for PNG 1x is 1000, for SVG is 500, and for PDF is 200.",
    "When initiating an approval request for an asset, generate a new cycle and ensure that a gmail thread is consistently maintained during the entire process.",
    "The sla_deadline_ts field should have a default value set to 2024-08-28T12:30:00Z.",
    "The standard format for the subject line of email threads pertaining to reviews is 'Design Review: <filename>'.",
    "The standard html body format for an email thread concerning a review is '<p>Review for the <filename>. See attachment.</p>'",
    "The standard html body format for an email thread regarding a request for changes is '<p>Requesting changes: <message>.</p>'",
    "The standard html body format for an email thread pertaining to changes implementation is '<p>Changes implemented: <message>.</p>'",
    "The standard html body format for an approval-related email thread is '<p>Approved: <message>.</p>'.",
    "The standard html body format for an email thread about a new release is '<h2>Release Notes - <release_name></h2>'. The set of current_labels for a review-related email thread must contain the labels 'Design/Needs-Review', 'figma', and 'review'.",
    "The set of current_labels for a release-related email thread must include 'Design/Release'.",
    "When a new review cycle is created, its initial value for status is set to IN_FLIGHT, and for review tasks, the status is updated to NEEDS_REVIEW.",
    "To approve, set the review cycle status to APPROVED; to request changes, update the review cycle status to CHANGES_REQUESTED.",
    "For both approval and change request actions on a review cycle, a comment and a message must be generated within the email thread.",
    "Comments between gmail and figma must be synchronized: when a user submits a review, the user must also post a comment with the content 'Submitted for review'. If a change is requested, the comment content should be 'Requested changes'. When a change is implemented, the comment must state 'Changes implemented'. If the request is approved, the comment content should be 'Approved'.",
    "When creating a comment, the resolved_flag is set to False by default, except when the content is 'Changes implemented' or 'Approved'. For new artifacts, the default values are: artifact_type as FRAME, artifact_name as Hero Section, page_id as 1:2, and current_tags as ['user', 'settings'].",
    "The filename for a new artifact must follow the format <figma_file_id>_<frame_id_nullable>.png. The default deeplink pattern for creating a new artifact is 'https://www.figma.com/file/<filename>.png'. To locate a thread for a release note, the subject should be formatted as '<release_name> - Release Notes'. The default HTML body pattern for a release note is '<h2><release_name></h2><p>Highlights:</p><ul><li>Added frame <frame_id_nullable></li><li>Updated frame <frame_id_nullable></li><li>Removed frame <frame_id_nullable></li></ul>', which is determined by the count of added, updated, or removed frames. Stakeholders must be notified after release notes are published. When creating a new release, the default figma_file_id is figd_abcd1234, the version_tag format is 'release/<tag>', and component_version_bumps is set to ['App update']. The version id for a new release must be extracted from the release_name and should follow the format v<version>. The changelog_highlights pattern for a new release should reflect the counts of added, updated, and removed frames (when greater than zero), using the format ['Added <number of added frames> frames', 'Updated <number of updated frames> frames', 'Removed <number of removed frames> frames']. For each new release, artifacts and assets should be created only for the added frames. Before vs after visuals are to be generated solely for the output and are not to be used as input.",
]
