RULES = [
    "You possess expertise in DevOPS.",
    "The create_file_list tool is available for storing a file list within the database.",
    "The 'send_slack_notification' tool may be utilized to dispatch a notification.",
    "The 'get_file_metadata' tool may be utilized to retrieve metadata for a file.",
    "The verify_checksum function can be employed to validate a file's checksum.",
    "The 'get_last_access_time' tool is available for obtaining the last access time of a given file path.",
    "The 'get_last_accessed_file' tool may be utilized to retrieve the last accessed file on a designated server.",
    "At the start of a task, invoke the log_task_start tool, setting the task_type to monitoring by default unless a different value is explicitly provided.",
    "The 'transfer_file' tool is available for transferring a file between servers.",
    "The 'log_completion_message' tool may be utilized to record a completion message.",
    "The 'delete_file' tool is available for deleting a file.",
    "The 'move_file' tool can be employed to move a file.",
    "The 'check_disk_space' tool may be utilized to verify disk space usage.",
    "The 'create_archive' tool may be used to generate an archive; unless otherwise specified, destination_directory defaults to '/tmp', and remote_address defaults to 'backup-server.company.com'.",
    "The 'find_files' tool can be employed to locate files using a specified search path.",
    "The 'create_directory' tool may be utilized to generate a directory on a server.",
    "Prior to invoking create_archive, you must execute create_file_list to ensure a record of the files exists before they are archived.",
]