WIKI = """
"Each task is required to perform a minimum of one database write operation (such as SG update, secret, cache setting, job run, schedule, alarm, cart, pricebook entry, promotion, context rule, or change log).",
    "IDs must be represented as strings; numeric IDs should not be transmitted as integers under any circumstances.",
    "The current time is set to '2025-08-06T12:00:00Z' and does not change.",
    "When an environment is not specified in the instruction, default to 'UAT'.",
    "Permitted environments are: 'DEV', 'UAT', and 'PROD'.",
    "The cache cluster id for UAT is 'dcomm-uat-redis'.",
    "UAT cache endpoint is set to: 'dcomm-uat-redis.abcdef.ng.0001.use1.cache.amazonaws.com'.",
    "The following service names are used: 'Commerce API', 'Checkout Gateway', and 'Cache Integration'.",
    "Standard product codes include: 'AC-USBC-HUB' for USB-C Hub and 'HW-TB-DOCK' for Thunderbolt Docking Station.",
    "Shared pricebooks include: 'Standard Retail', 'B2B Wholesale'.",
    "Shared promotions consist of: 'WELCOME5', 'WINTER20', 'B2BVOLUME15'.",
    "Monitoring baseline (cache): set up a 'cache' dashboard; configure an 'Errors' alarm with a threshold of 1.0 over 300 using 'GreaterThanOrEqualToThreshold'; execute the 'SMOKE' test.",
    "Monitoring baseline (API): set up an 'api' dashboard; configure a '5xxErrorRate' alarm with a threshold of 1.0 over 300 using 'GreaterThanOrEqualToThreshold'; execute the 'SMOKE' test.",
    "Secure to standard internal network: allow ingress from CIDR '10.0.0.0/16'; permit port 443; also permit port 6379 if Redis is included in the scope.",
    "Private ElastiCache baseline: specify service 'com.amazonaws.us-east-1.elasticache'; if VPC/subnets are explicitly stated in the instruction, apply them as written; if not, retrieve environment defaults and use those resulting outputs.",
    "Cache hardening baseline: utilize the current cluster specified in the instruction; activate Redis AUTH and TLS; retain the present partition key unless a new version is specified in the instruction.",
    "Prior to making network or security updates, retrieve environment defaults using get_environment_network_defaults, except when explicit VPC or subnet ids are supplied in the instruction.",
    "When restricting a service, modify the security group for that specific service (service_name must exactly correspond to the instruction).",
    "Security group ports/CIDRs are required to correspond exactly to either the instruction or the baseline rules (never created arbitrarily).",
    "Before making any modifications to the cluster or integrating it, always execute get_cache_cluster to read the cluster.",
    "If an instruction specifies 'keep <PROMO> active' or 'make sure <PROMO> is active', you must first call get_offer_by_code(<PROMO>), followed by an explicit upsert_promotion(code=<PROMO>, active=True).",
    "If an instruction includes 'pause <PROMO>' or 'deactivate <PROMO>', first execute get_offer_by_code(<PROMO>), followed explicitly by upsert_promotion(code=<PROMO>, active=False).",
    "Whenever rule names appear in natural language (such as VIP prefer EXPRESS or NewCustomers prefer STANDARD), and the rules are identified as 'Prefer-Express' or 'Prefer-Standard', use those precise strings as the value for rule_name_hint.",
    "set_redis_auth_and_tls: if not explicitly set, AUTH and TLS are both enabled by default.",
    "configure_cache_integration: utilize the cluster endpoint URL along with a secret ARN obtained from a previous step; if the instructions specify a partition key as 'dcomm-<env>' or 'dcomm-uat', use that value; otherwise, retain the existing key.",
    "The cache monitoring baseline must also perform a rapid metadata warm by executing run_cache_warm_jobs(mode='metadata').",
    "If the instructions specify that connected-app 'secrets' are needed or already 'in place', generate BOTH OAUTH_CLIENT_SECRET and API_AUTH_HEADER using create_secret_for prior to logging the modification.",
    "The default connected-app access required is ['api','openid'
"""
