WIKI = """
"Only candidate_ids present in candidates.json may be used; creation of new candidate_ids is prohibited.",
    "Candidate updates must be deterministic; when several updates are possible, applying any valid update is permitted.",
    "Asset requests must be updated utilizing IDs from asset_requests.json. When there are multiple requests, it is permissible to update only a subset, provided the final state aligns with the instructions.",
    "Assignments should align with approved requests whenever possible. If approval steps are absent but the assignment is valid within the dataset, it is still acceptable.",
    "Checklist items must refer to checklist_items.json. It is permissible to complete only some items if the entire set is not defined.",
    "Terminal logs indicating checklist completion should be captured whenever feasible; however, their absence is allowed as long as the corresponding updates are valid.",
    "Access checks are required to utilize candidate_ids and types specified in access_checks.json. Approving the complete set is recommended, but partial approval is also permitted.",
    "Terminal logs documenting access approvals must be captured; however, if they are absent, partial credit may be granted.",
    "When available, utilize the current file paths and candidate_ids from attachments/onboarding_files.json; if these are not present, new ids may be used.",
    "Terminal logs for file updates must be recorded; nonetheless, if the logs are missing but the updates are accurate, this is permissible.",
    "When performing add_attachment actions, utilize existing Attachment IDs from the dataset whenever possible. New IDs may be generated only if they accurately correspond to a new or supplementary attachment and do not duplicate any existing dataset entries.",
    "Select email_ids and label_ids exclusively from emails/email_labels.json. It is permissible to apply labels to only a subset of items.",
    "Ensure that terminal logs related to email labeling are captured; however, the absence of these logs is permissible provided that the labels have been applied correctly.",
    "Every action must target the end state specified in the instructions. Skipping intermediate steps or logs is acceptable as long as the final state aligns with the instruction.",
    "Do not create new IDs or records that do not exist within the datasets. Actions should be validated against the datasets whenever feasible.",
    "The instruction is required to explicitly define the intended end state or result for the task.",
    "Procedural language (such as 'approve', 'assign', or 'send') may be used, provided the instruction still clearly communicates the intended overall outcome.",
    "Tasks are deemed valid when the reader can discern the desired final state without requiring detailed, step-by-step instructions.",
    "Explicit actions (including release, assign, remove, add, attach, apply, complete, log, update) may be specified within instructions to enhance clarity, even if they take the form of procedural steps, as long as the primary objective or resulting state is explicitly stated.",
    "Including procedural steps within an instruction is permitted provided that the instruction also communicates the primary objective or intended result of the task. Detailed step-by-step directions should not be penalized if they enhance understanding.",
    "When logging actions with free-text messages (such as in record_terminal_log), variations in wording are allowed as long as they accurately represent the resulting outcome or change in state. Slight differences in phrasing are permissible, but messages that do not pertain to the event are not.",
"""
