RULES = [
    "Each task is required to perform a minimum of one database write operation (such as SG update, secret, cache setting, job run, schedule, alarm, cart, pricebook entry, promotion, context rule, or change log).",
    "IDs must be represented as strings; numeric IDs should not be transmitted as integers under any circumstances.",
    "The current time is set to '2025-08-06T12:00:00Z' and does not change.",
    "When an environment is not specified in the instruction, default to 'UAT'.",
    "Permitted environments are: 'DEV', 'UAT', and 'PROD'.",
    "The cache cluster id for UAT is 'dcomm-uat-redis'.",
    "UAT cache endpoint is set to: 'dcomm-uat-redis.abcdef.ng.0001.use1.cache.amazonaws.com'.",
    "The following service names are used: 'Commerce API', 'Checkout Gateway', and 'Cache Integration'.",
    "Standard product codes include: 'AC-USBC-HUB' for USB-C Hub and 'HW-TB-DOCK' for Thunderbolt Docking Station.",
    "Shared pricebooks include: 'Standard Retail', 'B2B Wholesale'.",
    "Shared promotions consist of: 'WELCOME5', 'WINTER20', 'B2BVOLUME15'.",
    "Monitoring baseline (cache): set up a 'cache' dashboard; configure an 'Errors' alarm with a threshold of 1.0 over 300 using 'GreaterThanOrEqualToThreshold'; execute the 'SMOKE' test.",
    "Monitoring baseline (API): set up an 'api' dashboard; configure a '5xxErrorRate' alarm with a threshold of 1.0 over 300 using 'GreaterThanOrEqualToThreshold'; execute the 'SMOKE' test.",
    "Secure to standard internal network: allow ingress from CIDR '10.0.0.0/16'; permit port 443; also permit port 6379 if Redis is included in the scope.",
    "Private ElastiCache baseline: specify service 'com.amazonaws.us-east-1.elasticache'; if VPC/subnets are explicitly stated in the instruction, apply them as written; if not, retrieve environment defaults and use those resulting outputs.",
    "Cache hardening baseline: utilize the current cluster specified in the instruction; activate Redis AUTH and TLS; retain the present partition key unless a new version is specified in the instruction.",
    "Prior to making network or security updates, retrieve environment defaults using get_environment_network_defaults, except when explicit VPC or subnet ids are supplied in the instruction.",
    "When restricting a service, modify the security group for that specific service (service_name must exactly correspond to the instruction).",
    "Security group ports/CIDRs are required to correspond exactly to either the instruction or the baseline rules (never created arbitrarily).",
    "Before making any modifications to the cluster or integrating it, always execute get_cache_cluster to read the cluster.",
    "If an instruction specifies 'keep <PROMO> active' or 'make sure <PROMO> is active', you must first call get_offer_by_code(<PROMO>), followed by an explicit upsert_promotion(code=<PROMO>, active=True).",
    "If an instruction includes 'pause <PROMO>' or 'deactivate <PROMO>', first execute get_offer_by_code(<PROMO>), followed explicitly by upsert_promotion(code=<PROMO>, active=False).",
    "Whenever rule names appear in natural language (such as VIP prefer EXPRESS or NewCustomers prefer STANDARD), and the rules are identified as 'Prefer-Express' or 'Prefer-Standard', use those precise strings as the value for rule_name_hint.",
    "set_redis_auth_and_tls: if not explicitly set, AUTH and TLS are both enabled by default.",
    "configure_cache_integration: utilize the cluster endpoint URL along with a secret ARN obtained from a previous step; if the instructions specify a partition key as 'dcomm-<env>' or 'dcomm-uat', use that value; otherwise, retain the existing key.",
    "The cache monitoring baseline must also perform a rapid metadata warm by executing run_cache_warm_jobs(mode='metadata').",
    "If the instructions specify that connected-app 'secrets' are needed or already 'in place', generate BOTH OAUTH_CLIENT_SECRET and API_AUTH_HEADER using create_secret_for prior to logging the modification.",
    "The default connected-app access required is ['api','openid'] unless the instruction specifically enumerates other scopes.",
    "The cache warm modes are: 'metadata' (quick) and 'populate' (full). Apply the mode specified in the instruction; if no mode is specified but a warm is implied by baseline, select 'metadata'.",
    "Cache alarms should be set to the *real* cluster id (such as 'dcomm-uat-redis'), except when the instruction explicitly specifies a different resource.",
    "During cache warmer deployment, the app_name/service_name must exactly match the service name provided in the instruction.",
    "For Lambda schedules and alarms, always use the complete ARN returned by deploy; do not use a short id or function name.",
    "When a monitoring baseline is requested but cadence/thresholds are not defined, apply the Monitoring baseline values.",
    "API rollout: first, publish the spec, then enable the gateway group, and next register the endpoints; if a monitoring baseline (API) is requested, proceed to create the 'api' dashboard, set up the 5xxErrorRate alarm, and execute SMOKE.",
    "Trace sampling: when requested without a specified value, default to 0.10.",
    "The change log target for rollout must correspond to the spec id ('spec-...').",
    "Connected apps: The app_name_hint field must exactly match the instruction (for example, 'Checkout API', 'Commerce API'). The generated app_id should be 'app-' followed by the slugified app_name using hyphens.",
    "Secrets (create_secret_for): The permitted values for purpose are 'OAUTH_CLIENT_SECRET' and 'API_AUTH_HEADER'. The value_source_id must correspond to the specific source explicitly named in the instruction, such as a cluster id like 'dcomm-uat-redis' or the connected app id from the previous output.",
    "Following any connected-app modifications, if a monitoring baseline is specified, execute 'OAuth-Smoke' and generate the 'api' dashboard.",
    "Always reference products in pricebooks or carts using the *external product_code* (such as 'AC-USBC-HUB', 'HW-TB-DOCK'); do not use internal numeric ids under any circumstances.",
    "To update pricebooks, apply upsert_pricebook_entries_batch with both product_code and unit_price; creating new pricebooks is not permitted.",
    "Promotions must be managed exclusively through the promotion path: retrieve using get_offer_by_code, and modify status with upsert_promotion (do not use upsert_offer for activating or pausing promotions).",
    "Cart creation: In cases where shipping is unspecified, assign 'STANDARD' as the default. Permitted shipping methods include: 'STANDARD', 'EXPRESS', and 'OVERNIGHT'.",
    "If a customer tier is referenced, invoke set_pricing_tier_for_customer to apply it prior to cart creation.",
    "If instructed to 'record the change for X', ensure that X is logged precisely as target_id.",
    "When change_type is unspecified: assign 'rollout' for API spec rollout, 'oauth' for connected-app modifications, 'networking' for VPC/SG/endpoint tasks, 'personalization' for context rules, and 'ops' for cache, pricebook, cart, secret, or integration activities.",
    "Permitted comparison tokens are: 'GreaterThanOrEqualToThreshold' and 'LessThanThreshold'.",
    "Permitted metrics include: 'Errors', 'CacheHitRate', and '5xxErrorRate'.",
    "Standard test collections include: 'SMOKE', 'OAuth-Smoke', 'Context-Rule-SMOKE', 'Pricing-SMOKE', and 'Gateway-SMOKE'.",
    "Avoid creating products, pricebooks, offers, endpoints, VPCs, or subnets that do not already exist. Always retrieve them beforehand, or utilize the precise literals specified in the instruction.",
    "Do not alter names: service and app names must be used exactly as provided in the instruction when input into tools.",
    "Avoid supplying literals that have not been explicitly declared. For any value not specified in the instruction, a previous output, or within these rules, either retrieve the value as needed or exclude the argument if the tool provides a safe default.",
    "When VPC or subnet ids are specified in the instruction, refrain from invoking environment defaults that might supersede the provided ids.",
    "In cases where multiple writes are performed, guarantee that at least one log entry is created to ensure the change is auditable.",
]
