RULES = [
    "Prior to performing write operations, confirm the existence of the target using stable identifiers (employee_id, account_id, mailbox_id, asset_id). If any required record is absent, do not fabricate data—log a validation issue and terminate the process.",
    "RBAC baselines are to be sourced from rbac_group_map based on (department, job_title); only assign ad-hoc groups if they are explicitly specified in the task.",
    "Every change to group membership must be recorded in group_membership_audit, including both the actor and the timestamp.",
    "Directory accounts: assign status exclusively as either 'enabled' or 'disabled'. During offboarding, ensure disabling occurs before any group removals.",
    "Mailboxes are required to comply with departmental retention policies. Assign 'finance_7y' for Finance; all other departments default to 'std_2y'.",
    "License assignments must comply with inventory constraints: used_seats plus reserved_seats must not exceed total_seats. If available capacity is lacking, generate a TaskTrack ticket labeled 'License Shortage', refrain from exceeding allocation limits, and update the lifecycle or ticket status to blocked or on hold as appropriate.",
    "Updating license_assignments and license_inventory used_seats during license assign or revoke operations must occur atomically, ensuring used_seats never becomes negative.",
    "Asset provisioning selects from it_assets with status='in_stock', prioritizing the earliest purchase_date, and using lexicographic order of asset_id to resolve ties.",
    "Both MDM enrollment and device handoff actions are to be recorded in device_workflow, with a deterministic pickup_code supplied by the caller.",
    "Device_workflow actions for returns must be created with due_ts as specified in the memo or instruction; asset ownership should remain unchanged until the return process is finalized.",
    "Ticket status changes must follow valid transitions: New may proceed to In Progress or On Hold, then to Resolved, and finally to Closed; alternatively, New may transition directly to Closed in the case of cancellations.",
    "Daily metrics and backlog snapshots are to be calculated deterministically using tickets filtered strictly by the explicitly supplied windows.",
    "Any shortages or system blockers must have corresponding TaskTrack tickets (issue_type in 'License Shortage', 'Hardware Shortage', 'Incident', or 'Bug'), and the associated lifecycle should be set to 'blocked' or the ticket status updated to 'On Hold'.",
    "For onboarding: first, enqueue the lifecycle; next, sequentially perform baseline RBAC, assign licenses, provision assets with MDM, create app accounts, conduct mailbox checks, and only set the lifecycle to 'completed' if there are no shortages present.",
    "During offboarding: begin by disabling sign-in, then remove group memberships, revoke licenses (and reduce seat counts), archive the mailbox according to retention policy, arrange device returns, notify the manager (simulated), and finally update the lifecycle to 'completed'.",
    "Tools must not create random IDs or use dynamic timestamps; instead, all IDs and timestamps must be explicitly provided or deterministically calculated based on the current table length, ensuring stability given the same initial state and sequence of actions.",
    "If several valid options are available (such as assets or licenses), use the tie-breaker and include the selected IDs in the outputs whenever the task requests them.",
    "If any required inputs are absent or inconsistent, generate a validation_issues entry containing the relevant details and halt processing, avoiding any assumptions or guesses.",
]
