RULES = [
    "Always determine the customer’s identity first by using the email address to retrieve their contact information and account context.",
    "The permitted shipping methods are Us-Std, US-Std, EU-Std, US-Priority, EU-Priority, EU-Express, and US-Express; no other shipping methods are allowed, and capitalization must be matched exactly.",
    "The currency gateway configuration must support both USD and EUR payments when the shipping destination is within the EU, and only USD payments when the shipping method is US-Std.",
    "The purchase process must follow this sequence: identify the customer → browse products in the catalog → obtain a new cart number → create the cart with selected items → obtain a new order number → submit the order.",
    "Identifiers must never be fabricated. A new cart number must be obtained prior to cart creation, and a new order number must be obtained before order placement.",
    "Apply the discount code to the cart once it has been created and prior to initiating the order number request.",
    "Handle all identifiers provided to the platform—including cart, order, contact, account, app, cluster, security group, product, backup, and others—as strings.",
    "The permitted discount codes are: WELCOME5, WINTER20, B2BVOLUME15, except when a different code is explicitly specified in the instruction.",
    "Process returns exclusively for orders generated within this task, or when a specific order id is provided.",
    "Access the audit log solely if the instruction requests verification; otherwise, refrain from unnecessary audit log reads.",
    "For cache security, follow this sequence: first provision or attach the cache, next limit Redis 6379/TCP access to CIDR 10.0.0.0/16 on the designated security group (sg-0123456789abcdef0), and finally, reconcile or optimize the security group rules.",
    "If no cache capacity is provided, use node type ‘cache.r5.large’ and allocate three nodes by default.",
    "Permit a temporary TLS rule for 6380/TCP solely upon request; once completed, revert to 6379/TCP with CIDR 10.0.0.0/16.",
    "Once a rate limit is applied to an endpoint, retrieve the current limit for that endpoint to verify the update.",
    "Once you enable or update a connected app’s security, verify the configuration by reviewing the app’s security details.",
    "When instructed to confirm cache readiness, retrieve and review the status or details of the cluster using the same cluster id.",
    "When an instruction refers to a backup, first record the backup, then retrieve its metadata.",
    "When shipping rules exist for a customer and a purchase is made, apply the identical customer identity during both shipping and checkout processes.",
    "If platform preludes (such as cache hardening, app security, rate limits, marketing/segments, and backups) are to be combined with a purchase, ensure all preludes are finalized prior to initiating the purchase flow, maintaining the prescribed sequence.",
    "Identify products prior to initiating cart creation.",
    "Do not terminate the process at the point of cart creation. When a purchase is initiated, the process is only considered complete after any applicable discount has been applied to the cart, a new order number has been retrieved, and the order has been submitted. The resulting output must contain the order id as a string.",
    "If the task specifically instructs to check something in audit (such as a security-group optimization or a backup), access that audit only after the change has been made and the order has been submitted; otherwise, audits should not be accessed.",
    "Apply any discount once the cart has been created and prior to requesting the order number.",
    "Obtain a cart number prior to creating a cart; obtain an order number prior to placing the order.",
    "When a return is required, it must be processed only after the order has been placed.",
    "For any task related to a specific customer (purchase, shipping, loyalty, recommendations, segments, pricing), start by identifying the customer using their email; do not execute app security, rate limit adjustments, cache/CDN operations, backups, campaigns, or recommendations until customer identification is complete—unless the task pertains exclusively to infrastructure without any customer context.",
    "Rely exclusively on the platform’s stated capabilities; do not infer or presume any others.",
    "Start by locating the customer through the email specified in the task. If the email is missing or the profile cannot be located, refrain from making assumptions or using an alternative identity.",
    "When handling tasks related to purchase, shipping, loyalty, recommendations, segments, or pricing, ensure the customer is identified prior to performing any other customer-specific setup.",
    "Purchase flow (mandatory sequence): first, identify the customer → next, locate the product in the catalog → then, obtain a new cart number → create the cart including the items → subsequently, acquire a new order number → finally, place the order.",
    "Never generate identifiers arbitrarily. Always obtain new numbers for carts and orders through requests, and utilize those exact values as provided.",
    "Handle all platform identifiers as strings (including cart, order, contact, account, app, cluster, security group, product, backup, and others).",
    "Pass only those parameters included in the documented capability; avoid including any optional fields that have not been explicitly requested.",
    "If a task instructs to ‘launch’ or ‘run’ a specific campaign by name (such as ‘RET-10’), interpret this as initiating a promotion where the numeric portion of the name represents the percentage value (for example, RET-10 corresponds to 10%).",
    "If a task requests to ‘see’ or ‘get’ recommendations (such as similar products or bought-together items), interpret this as a recommendation request rather than a campaign.",
    "Unless specified differently in the task, apply these defaults: High-Value-90d = {min_orders: 5, last 90 days}; Returning-30d = {min_orders: 2, last 30 days}; Returning-60d = {min_orders: 2, last 60 days}.",
    "Configuration tasks are required to include precise numeric targets and regions. Do not use ambiguous terms such as ‘a reasonable limit’ or ‘primary region’. If a limit or region is missing, request clarification rather than making assumptions.",
    "If a task instructs you to confirm a change, repeat the current settings for the same target (for instance, restate the rate limit for the relevant endpoint, the security configuration for the specified connected app, or the cache cluster status for the particular cluster).",
    "Access the audit log solely if the task specifically instructs you to check something in audit; otherwise, do not perform audit reads.",
    "Do not reuse any cart number previously utilized within the same task; instead, always request a new cart number right before cart creation.",
    "Apply any discount code once the cart has been created and prior to requesting the order number.",
]
