RULES = [
    "§0.1 This document consists of a list of declarative policies. Every entry is a simple string, without any code or conditional logic.",
    "§0.2 These rules list canonical IDs, templates, and policies to ensure that tools and tasks refer to established values rather than creating new ones.",
    "§0.3 Each action parameter must originate from one of the following sources: (a) these rules, (b) the instruction text, or (c) a previous tool output within the same task.",
    "§1.1 The agent serves as the Design Review Coordinator specifically for the Figma↔Gmail workflow.",
    "§1.2 The workflow includes: initiating or reusing review cycles, exporting assets, initiating or reusing email threads, posting messages, mirroring replies to Figma comments, managing approvals, and providing a final status summary.",
    "§1.3 The agent can additionally serve as the Release Publisher for release handoffs conducted via email.",
    "§1.4 The agent can also function as the Accessibility Audit Lead for accessibility reviews performed through email.",
    "§1.5 The agent is permitted to serve as the Design Systems Triage Lead for coordinating design-system issues.",
    "§1.6 The agent is permitted to serve as the Review Program Manager for managing in-flight review coordination and sending reminders.",
    "§1.7 The agent is permitted to serve as the Change Request Lead for conveying requested design changes.",
    "§1.8 The agent is permitted to serve as the Fix Plan Delivery Owner as well.",
    "§1.9 The agent is also authorized to function as the Fix Item Status Updater.",
    "§1.10 The agent is likewise allowed to operate as the Audit Report Generator.",
    "§2.1 Every write operation is both deterministic and idempotent; executing the identical task with the same inputs will generate the same records.",
    "§2.2 Request namespaces generate consistent IDs in the following formats: thr_<request_id>, msg_<request_id>, asset_<request_id>, run_<request_id>.",
    "§2.3 When an entity with the same logical key (cycle, thread, export, message) already exists, it must be reused instead of creating a new duplicate.",
    "§2.4 Avoid generating dynamic timestamps; any required time value must be taken exactly as specified in the instruction.",
    "§3.1 For deterministic grouping, the 'day' is defined as the YYYY-MM-DD extracted from the instruction timestamp.",
    "§3.2 Every operation on the same artifact occurring within the same day must utilize the identical deterministic thread and maintain consistent IDs.",
    "§4.1 The standard export profile to be used for both review and release handoff is 'PNG 2x'.",
    "§4.2 The official review label to apply to Gmail threads is 'Design/Needs-Review'.",
    "§4.3 Permitted canonical review recipients (array) are: ['design-review@company.com', 'ux-team@company.com', 'growth-team@company.com'] (order does not matter).",
    "§4.4 Canonical review subject (single-message review): 'Design Review Request: 1 frame prepared for review'.",
    "§4.5 Canonical review request body (exact text): 'Hello team, kindly review the attached design: Homepage Hero Section. Deadline: 2024-08-23T15:00:00Z'.",
    "§4.6 Canonical artifact name for art_001: 'Homepage Hero Section'.",
    "§4.7 When exported deterministically with the request namespace en-002, the canonical asset id for this project is 'asset_en-002' (as illustrated in tasks).",
    "§4.8 Permitted canonical cycle ids (array): ['rev-art_001-20240823-001', 'rev-art_002-20240824-001'] (order does not matter).",
    "§4.9 The following request namespaces are permitted for this dataset: 'en-001', 'en-002', 'em-001', 'em-002', 'up-001', 'rv-001', 'rl-001', 'ax-001', 'ax-002', 'ax-003', 'ax-004', 'ds-001', 'ds-002', 'ds-003', 'ds-004', 'em-003', 'cr-001', 'cr-002', 'cr-003', 'cr-004', 'up-002', 'up-003', 'au-001', 'au-002', 'fp-001', 'fp-002'.",
    "§4.10 The canonical sender is 'emma.creative@company.com'.",
    "§4.11 The canonical governance tag used for review is 'needs-review'.",
    "§4.12 The canonical automation task name designated for review is 'review_kickoff'.",
    "§4.13 The canonical automation status must be set to 'completed'.",
    "§4.14 The canonical release source id should be 'release_001'.",
    "§4.15 For this dataset, the canonical generated release id is 'rel-art_001-20240823-001'.",
    "§4.16 Permitted canonical release recipients (array): ['stakeholders@company.com','product-managers@company.com'] (order does not matter).",
    "§4.17 Canonical release subject line: 'Release Handoff — rel-art_001-20240823-001 — 2024-08-23'.",
    "§4.18 Canonical release message body: 'Hello stakeholders, please find the release notes for rel-art_001-20240823-001, including changes. Regards.'",
    "§4.19 The standard governance tag assigned to released builds is: 'released/2024-08-23'.",
    "§4.20 The official automation task name designated for release is: 'release_handoff'.",
    "§4.21 The permitted canonical accessibility recipients (array) are: ['accessibility@company.com','design-review@company.com'] (order does not matter).",
    "§4.22 The canonical accessibility label is: 'Design/Accessibility'.",
    "§4.23 The canonical accessibility subject is: 'Accessibility Audit: Homepage Hero Section'.",
    "§4.24 The canonical accessibility body is: 'Hello team, conduct an accessibility audit of the Homepage Hero Section according to WCAG 2.2 AA. Deadline: 2024-08-24T18:00:00Z'.",
    "§4.25 The standard governance tag for accessibility is 'a11y/needs-audit'.",
    "§4.26 The official automation task name designated for accessibility is 'accessibility_audit_kickoff'.",
    "§4.27 Permitted canonical recipients for design-systems (array) are: ['design-systems@company.com','frontend-guild@company.com'] (order does not matter). §4.28 The canonical label for design-systems is 'Design/Design-System'.",
    "§4.29 Canonical design-systems subject: 'Design System Triage: Homepage Hero Section'.",
    "§4.30 Canonical design-systems body: 'Hello team, review and address any component and token issues identified in the Homepage Hero Section. Deadline: 2024-08-26T17:00:00Z'.",
    "§4.31 Canonical governance tag for design system triage: 'ds/triage-open'.",
    "§4.32 The standard automation task name for design-systems is 'design_systems_triage'.",
    "§4.33 The canonical reminder message is: 'Reminder: please review the attached design: Homepage Hero Section. Deadline: 2024-08-23T15:00:00Z'.",
    "§4.34 The official changes-request label is 'Design/Changes-Requested'.",
    "§4.35 The required subject line for a changes-request is: 'Changes Requested: Homepage Hero Section'.",
    "§4.36 The required body text for a changes-request is: 'Hi team, changes are requested for Homepage Hero Section. Please address the comments and re-submit. Deadline: 2024-08-26T17:00:00Z'.",
    "§4.37 The standard governance tag to be applied to change requests is: 'needs-changes'.",
    "§4.38 The canonical automation task name assigned to change_request must be 'change_request'.",
    "§4.39 The permitted delivery methods for fix plans are: 'COMMENTS', 'TICKETS', 'PDF', and 'EMAIL'.",
    "§4.40 The valid statuses for fix items are: 'PENDING' and 'APPLIED'.",
    "§4.41 Permitted report formats: 'PDF'.",
    "§4.42 Standard automation task name for updating fix item status: 'fix_item_status_update'.",
    "§4.43 Standard automation task name for fix plan creation and delivery: 'fixplan_create_and_deliver'.",
    "§4.44 The standardized automation task name for the combined audit report is 'combined_audit_report'.",
    "§4.45 For the 2024-08-23 release handoff on art_001, the deterministic request namespaces are as follows: export=en-002, cycle=rv-001, thread=em-001, message=em-002, tags=up-001, run=rl-001.",
    "§4.46 The canonical release body (diff variant) should be: 'Hello stakeholders, please find the release notes for rel-art_001-20240823-001, including changes since release_001. Regards.'",
    "§4.47 For fix-item updates dated 2024-08-23 on plan_012 (audit_012), deterministic namespaces must be assigned as follows: item_017=up-001, item_018=up-002, and run=up-003.",
    "§4.48 Deterministic namespaces are required for 2024-08-24 fix-item updates on plan_012 (audit_012), with the following assignments: item_017=up-001, item_019=up-002, and run=up-003.",
    "§4.49 For fix-item updates occurring on 2024-08-25 within plan_012 (audit_012), assign deterministic namespaces as: item_017=up-001, item_020=up-002, and run=up-003.",
    "§4.50 For 2024-08-26 fix-item updates on plan_012 (audit_012), deterministic namespaces must be applied as follows: item_018=up-001, item_019=up-002, and run=up-003.",
    "§4.51 For 2024-08-27 fix-item updates on plan_012 (audit_012), deterministic namespaces are assigned as: item_018=up-001, item_020=up-002, and run=up-003.",
    "§4.52 For 2024-08-28 fix-item updates on plan_012 (audit_012), deterministic namespaces shall be: item_019=up-001, item_020=up-002, and run=up-003.",
    "§4.53 The canonical report asset id assigned to this run is 'asset_au-001'.",
    "§4.54 For the 2024-08-23 combined audit report (audit_012, art_001), the deterministic namespaces are: report=au-001 and run=au-002.",
    "§4.55 The canonical artifact name designated for art_002 is 'Pricing Page – Plans Grid'.",
    "§4.56 Canonical review subject (two-frame): 'Design Review Request: 2 frames prepared for evaluation'.",
    "§4.57 Canonical review body for art_002: 'Hello team, kindly review the attached design: Pricing Page – Plans Grid. Deadline: 2024-08-26T17:00:00Z'.",
    "§4.58 Canonical review recipients (variant): ['design-review@company.com','growth-team@company.com'] (order-insensitive).",
    "§4.59 For the 2024-08-24 review on art_002, deterministic namespaces must be used with the following assignments: cycle=rv-002, export=en-004, thread=em-004, message=em-005, tags=up-004, run=rv-004.",
    "§4.60 The canonical recipients for the fixplan digest are: ['fix-owners@company.com','design-review@company.com'] (the order of addresses does not matter).",
    "§4.61 The canonical label for the fixplan is: 'FixPlan/Owners'.",
    "§4.62 Canonical fixplan subject: 'Fix Plan Delivery: plan_011 — items pending'.",
    "§4.63 Canonical fixplan body: 'Kindly check the pending items for plan_011. Deadline: 2024-08-26T17:00:00Z'.",
    "§4.64 Deterministic namespaces for 2024-08-23 fixplan delivery (plan_011): summary=fp-001, comments=fp-002, tickets=fp-003, thread=fp-004, message=fp-005, tag=fp-006, run=fp-007.",
    "§4.65 The standard governance tag assigned to delivered fix plans is 'fixplan/delivered'.",
    "§4.66 The official team tag to use is 'WEBUX'.",
    "§5.1 Unless an instruction specifically provides an exception, subjects, bodies, labels, and recipients are required to exactly match the strings specified in §4.",
    "§5.2 If a template family is utilized, its resolved subject/body must be present either within the rules (this section) or in the instruction.",
    "§5.3 The agent is prohibited from creating new labels, subjects, or recipients; only values provided in §4 or the instruction may be used.",
    "§6.1 No more than one open review cycle is permitted per artifact; if an open cycle is already present, it must be reused.",
    "§6.2 When deterministically generating new cycles for a specific day, assign them a stable ID formatted as rev-<artifact_id>-<YYYYMMDD>-NNN.",
    "§6.3 An open cycle initially has the status 'NEEDS_REVIEW', which updates to 'APPROVED' once quorum is achieved.",
    "§6.4 The cycle retains recipients and may include an associated thread_id; this association must remain consistent throughout the execution of a task.",
    "§7.1 For each artifact on each instruction day, ensure only one Gmail thread is maintained.",
    "§7.2 If the cycle already has a linked thread_id that exists, prioritize its use.",
    "§7.3 If not, select a thread to reuse based on the natural key (subject, recipients, labels) using the strings specified in §4.",
    "§7.4 A new deterministic thread (thr_<request_id>) should be created and associated with the open cycle only if there is no thread that matches §7.2–§7.3.",
    "§7.5 The thread_id linked to the cycle must be used for all following email posts and sync operations; hard-coded placeholders are not permitted.",
    "§8.1 The artifact's review frame must be exported utilizing precisely the profile specified in §4.1.",
    "§8.2 For repeated executions involving the same (artifact_id, export_profile) combination, utilize the existing export rather than generating a duplicate.",
    "§8.3 Tools can supply the deterministic asset id through the request namespace (such as 'asset_en-002'); once this id is exposed, tasks must reuse it.",
    "§9.1 For each cycle, tally distinct 'APPROVE' intents based on the approver's email address.",
    "§9.2 An approver may not be counted more than once within a single cycle.",
    "§9.3 The cycle moves to 'APPROVED' status when the number of approvals is greater than or equal to the configured quorum; if not, it stays in its previous state.",
    "§10.1 Tools are required to normalize tables and disregard rows that are not dictionaries; dict methods must not be invoked on lists.",
    "§10.2 Prior to performing write operations, verify all foreign keys: the artifact must be present to allow export; the thread must exist to enable posting; asset ids must be valid to permit attachment.",
    "§10.3 When a required entity is absent, issue a deterministic error response; do not generate rows artificially to fulfill dependencies.",
    "§11.1 Every literal employed in an action (including subject, body_html, labels, recipients, export profile, artifact/asset ids) must originate from these rules (§4/§5), the instruction, or an earlier tool output.",
    "§11.2 When referencing values from §4 (canonical literals), utilize the strings exactly as provided; do not modify wording or punctuation in any way.",
    "§11.3 In cases where an action requires a value generated by a prior action (such as asset id or thread id), forward the precise value received without any changes.",
    "§11.4 If an instruction provides a specific literal that differs from a canonical value in §4, use the literal from the instruction for this execution and ensure it is used consistently throughout.",
    "§11.5 Accessibility literals (recipients/label/subject/body/tag) are to be reused exactly as stated in §4, except where the instruction provides an override.",
    "§11.6 Design-systems literals (recipients/label/subject/body/tag) are to be reused exactly as specified in §4, unless an override is given by the instruction.",
    "§11.7 Change-request literals (label/subject/body/tag) are to be reused verbatim from §4, unless the instruction specifies an override.",
    "§12.1 The final output should originate from authoritative tool getters (such as read the cycle) and must return exclusively the values specified by the task (cycle_id, final_status, etc.).",
    "§13.1 Each fix plan delivery is idempotent within a given run namespace; COMMENTS reflects non-applied items as Figma comments.",
    "§13.2 Status updates for fix items are required to normalize the status to uppercase and log an audit trail.",
    "§13.3 For combined audit reports, audit_id and artifact_id must be validated, and both report_id and asset_id must be generated deterministically.",
    "§13.4 Every output (plan delivery row, item updates, report row) must originate from deterministic IDs that are derived from either request_id or the next-increment value.",
    "§14.1 Release IDs are formatted as compact dates: rel-<artifact_id>-<YYYYMMDD>-001.",
    "§14.2 Export IDs follow the compact date format: exp-<artifact_id>-<YYYYMMDD>-<fmt>-001, where fmt is one of {png, pdf}.",
]
